# Generated by Django 6.0.3 on 2026-04-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Antrean',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_antrean', models.IntegerField()),
                ('status', models.CharField(choices=[('MENUNGGU', 'Menunggu'), ('DIPANGGIL', 'Dipanggil'), ('SELESAI', 'Selesai')], default='MENUNGGU', max_length=20)),
                ('waktu_dibuat', models.DateTimeField(auto_now_add=True)),
                ('waktu_dipanggil', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
