# Generated by Django 6.0.4 on 2026-06-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0002_antrean_keperluan_antrean_nama_antrean_nim'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanSistem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('butuh_dipanggil', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='antrean',
            options={'ordering': ['waktu_dibuat']},
        ),
        migrations.AlterField(
            model_name='antrean',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu'), ('proses', 'Sedang Proses'), ('selesai', 'Selesai'), ('terlewati', 'Terlewat / Tidak Hadir')], default='menunggu', max_length=20),
        ),
    ]
